### ISSUE TITLE
The APP don't track the step all the time

### ISSUE THREAD

**Issue by trungphan9x** [tiefensuche/motionmate#1]
Hi,

I tried to install your APP and Samsung health on the same phone last night. In the morning, I woke up and take the phone to go to work with me. Samsung health kept tracking the step while I was going to the company but your APP did not. I did not open the phone from last night until I was in the company.

Could you fix that problem?

**Comment by tiefensuche** [comment]
Hi,

I have some questions that could reveal the problem.

Did you installed the apk from the release page or did you built the project yourself? Have you tested the app right after you installed it and did it increased steps when moving? So when you opened the app after movement, it showed up with 0 steps?

The app should show a notification icon when it is running in the background that should also update and show the steps of the current day.

**Comment by trungphan9x** [comment]
@tiefensuche I tested again today, and it seems good today.
Thank you for your speedy support. 
If anything went wrong with it, I will let you know

Thx
